name = "modpack"
author = "Solariity & Kapsikkum"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33e9438651a4ca9a2a0f226ec2e59699b9923b16f3769b902c34c268420d53f6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
