name = "modpack"
author = "Solariity & Kapsikkum"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc0ca11d2ae4bfae7cdf22135b0b41cea5e5a72eeddef925a6e7b175e1b9bfb3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
