name = "modpack"
author = "Solariity & Kapsikkum"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba4e44698fcb80ca71aac2429b93bbcb869b1f3509b649160f0e566bd66d2373"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
