name = "modpack"
author = "Solariity & Kapsikkum"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82723d5f29f729009820b9c036f90bbbf7a04a835f852ab85baac526823b298e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
