name = "modpack"
author = "Solariity & Kapsikkum"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d44cb958ddab17603adf7a30c899056e5e5c9265001a77945bfd03c3cd5a29d6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
